#!/usr/bin/env ruby

site "https://supermarket.getchef.com/api/v1"

cookbook "inaturalist-cookbook", git: "git://github.com/pleary/inaturalist-cookbook.git"
cookbook "rvm", git: "git://github.com/fnichol/chef-rvm.git", ref: "v0.9.0"
cookbook "disable_ipv6", git: "git://github.com/rackspace-cookbooks/varnish.git", path: "test/fixtures/cookbooks/disable_ipv6"
cookbook "varnish", git: "git://github.com/rackspace-cookbooks/varnish.git"
cookbook "nodejs", git: "git://github.com/redguide/nodejs.git"
